yaml
version: '3'
services:
 web:
    build: .
    ports:
      - "80:80"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
 nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
